# Generated by Django 5.2.6 on 2025-10-13 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_high_c', models.FloatField(blank=True, null=True)),
                ('temp_low_c', models.FloatField(blank=True, null=True)),
                ('temp_high_f', models.FloatField(blank=True, null=True)),
                ('temp_low_f', models.FloatField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=100, null=True)),
                ('chance_of_rain', models.IntegerField(blank=True, null=True)),
                ('chance_of_snow', models.IntegerField(blank=True, null=True)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='events.event')),
            ],
        ),
    ]
