# Generated by Django 5.2.6 on 2025-11-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventweather',
            name='temp_high_c',
        ),
        migrations.RemoveField(
            model_name='eventweather',
            name='temp_high_f',
        ),
        migrations.RemoveField(
            model_name='eventweather',
            name='temp_low_c',
        ),
        migrations.RemoveField(
            model_name='eventweather',
            name='temp_low_f',
        ),
        migrations.AddField(
            model_name='eventweather',
            name='humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventweather',
            name='temp_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventweather',
            name='temp_f',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventweather',
            name='wind_mph',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
