# Generated by Django 5.2.6 on 2025-11-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_eventweather_temp_high_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='street_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
